### ISSUE TITLE
Unable to delete created folder

### ISSUE THREAD

**Issue by HarshaVardhanJ** [archivy/archivy#139]
## Description of Issue

After creating a new folder(titled `NewFolder`), I'm unable to delete it from the UI. The folder shows up again after I refresh the page.

## Logs

Given below are the logs pertaining to this error:

```
Setting environment variables.
The following environment variables were set:
		FLASK_DEBUG=0
		ELASTICSEARCH_ENABLED=0
		ELASTICSEARCH_URL=http://localhost:9200/
		ARCHIVY_PORT=5000
Elasticsearch not used. Search function will not work.
Starting Archivy
[2020-11-25 07:00:04,115] INFO in __init__: Archivy has created an admin user as it did not exist.
                            Username: 'admin', password: 'AAhNGlRIAMqRVlJOCfaNjyP5HBU4vED0iDKWdaO-Vnw'
                        
Running archivy...
[2020-11-25 07:00:04,542] INFO in check_changes: Running watcher
[2020-11-25 07:00:04,547] INFO in __init__: OUTPUT_FOLDER: /tmp/click-web
 * Serving Flask app "archivy" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.17.0.1 - - [25/Nov/2020 07:00:09] "GET /index HTTP/1.1" 302 -
172.17.0.1 - - [25/Nov/2020 07:00:10] "GET /login?next=%2Findex HTTP/1.1" 200 -
172.17.0.1 - - [25/Nov/2020 07:00:10] "GET /favicon.ico HTTP/1.1" 302 -
172.17.0.1 - - [25/Nov/2020 07:00:10] "GET /login?next=%2Ffavicon.ico HTTP/1.1" 200 -
172.17.0.1 - - [25/Nov/2020 07:00:13] "POST /login?next=%2Findex HTTP/1.1" 302 -
172.17.0.1 - - [25/Nov/2020 07:00:13] "GET /index HTTP/1.1" 200 -
172.17.0.1 - - [25/Nov/2020 07:00:13] "GET /favicon.ico HTTP/1.1" 404 -
172.17.0.1 - - [25/Nov/2020 07:00:25] "POST /api/folders/new HTTP/1.1" 200 -
127.0.0.1 - - [25/Nov/2020 07:00:32] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [25/Nov/2020 07:00:32] "GET /login?next=%2F HTTP/1.1" 200 -
[2020-11-25 07:00:33,832] ERROR in app: Exception on /api/folders/delete [DELETE]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/Flask-1.1.2-py3.9.egg/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/Flask-1.1.2-py3.9.egg/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/Flask-1.1.2-py3.9.egg/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/Flask-1.1.2-py3.9.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/Flask-1.1.2-py3.9.egg/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/Flask-1.1.2-py3.9.egg/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/archivy-0.8.4-py3.9.egg/archivy/api.py", line 167, in delete_folder
    if data.delete_dir(directory):
  File "/usr/local/lib/python3.9/site-packages/archivy-0.8.4-py3.9.egg/archivy/data.py", line 138, in delete_dir
    rmtree(get_data_dir() / name)
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'
172.17.0.1 - - [25/Nov/2020 07:00:33] "DELETE /api/folders/delete HTTP/1.1" 500 -
172.17.0.1 - - [25/Nov/2020 07:00:49] "GET /index HTTP/1.1" 200 -
172.17.0.1 - - [25/Nov/2020 07:00:49] "GET /static/profile.svg HTTP/1.1" 304 -
172.17.0.1 - - [25/Nov/2020 07:00:50] "GET /static/delete.png HTTP/1.1" 304 -
127.0.0.1 - - [25/Nov/2020 07:01:02] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [25/Nov/2020 07:01:02] "GET /login?next=%2F HTTP/1.1" 200 -
127.0.0.1 - - [25/Nov/2020 07:01:32] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [25/Nov/2020 07:01:32] "GET /login?next=%2F HTTP/1.1" 200 -
127.0.0.1 - - [25/Nov/2020 07:02:02] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [25/Nov/2020 07:02:02] "GET /login?next=%2F HTTP/1.1" 200 -
127.0.0.1 - - [25/Nov/2020 07:02:32] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [25/Nov/2020 07:02:32] "GET /login?next=%2F HTTP/1.1" 200 -
127.0.0.1 - - [25/Nov/2020 07:03:02] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [25/Nov/2020 07:03:02] "GET /login?next=%2F HTTP/1.1" 200 -
```

> **NOTE **: 
> This issue occurs in the docker image built from the source code in the `master` branch.

**Comment by Uzay-G** [comment]
Was this with an up to date version?

I can't seem to replicate this issue...

**Comment by Uzay-G** [comment]
Thanks for detecting this.

Fixed in https://github.com/archivy/archivy/commit/2df3a4a7dcaef308ee0b517a98529de245f44aa4
